// Generated by CoffeeScript 1.3.3
(function() {
  var Chord;

  Chord = (function() {

    function Chord(text) {
      this.text = text;
      console.log(this.text + "is a chord");
    }

    return Chord;

  })();

}).call(this);
